apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: microsegmentation-controller
spec:
  parentResource:
    apiVersion: v1
    resource: services  
  childResources:
    - apiVersion: extensions/v1beta1
      resource: networkpolicies
#    - apiVersion: networking.k8s.io/v1
#      resource: networkpolicies      
  clientConfig:
    service:
      name: microsegmentation-controller
      namespace: microsegmentation-controller
  hooks:
    sync:
      path: /sync
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: microsegmentation-controller
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - microsegmentation-controller
        from:
          kind: ImageStreamTag
          namespace: microsegmentation-controller
          name: 'microsegmentation-controller:latest'
  replicas: 1
  template:
    metadata:
      labels:
        app: microsegmentation-controller
    spec:
      containers:
      - name: microsegmentation-controller
        image: _
---
apiVersion: v1
kind: Service
metadata:
  name: microsegmentation-controller
spec:
  selector:
    app: microsegmentation-controller
  ports:
  - port: 80
    targetPort: 8080
    name: http