apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: microsegmentation-controller
spec:
  parentResource:
    apiVersion: v1
    resource: services
  childResources:
    - apiVersion: v1
      resources: ["networkpolicies"]
  clientConfig:
    service:
      name: microsegmentation-controller
      namespace: metacontroller
  hooks:
    sync:
      path: /sync
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: microsegmentation-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsegmentation-controller
  template:
    metadata:
      labels:
        app: microsegmentation-controller
    spec:
      containers:
      - name: microsegmentation-controller
        image: gcr.io/enisoc-kubernetes/nodejs-server:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: catset-controller
---
apiVersion: v1
kind: Service
metadata:
  name: microsegmentation-controller
  namespace: metacontroller
spec:
  selector:
    app: microsegmentation-controller
  ports:
  - port: 8080