apiVersion: v1
kind: Service
metadata:
  name: microsegmentation-controller-test
  annotations:
    io.raffa.microsegmentation: 'true'
    io.raffa.microsegmentation.additional-ports: 9999/tcp, 8888/udp
spec:
  selector:
    app: microsegmentation-controller-test
  ports:
  - port: 8080